name: grokking
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.1
  - numpy>=1.24.3
  - matplotlib>=3.7.1
  - tqdm>=4.65.0
  - pip
  - pip:
    - torchvision
